[tox]
skipsdist = True
envlist = py39, py310, py311, py312, lint

[testenv:lint]
deps =
    .[test]

allowlist_externals = 
    flake8p

commands =
    flake8p src/aicsshparam --count --verbose --show-source --statistics
    black --check src/aicsshparam

[testenv]
setenv =
    PYTHONPATH = {toxinidir}/src
deps =
    .[test]
commands =
    pytest --basetemp={envtmpdir} --cov-report html --cov=aicsshparam src/aicsshparam/tests/
